config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :trips
  resources :souvenirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "souvenirs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/souvenir.rb
class Souvenir < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
before_validation :hey
attr_accessor :myjob
def hey
self.job_id=Job.find_or_create_by(name: self.myjob)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: "Country was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy!

    respond_to do |format|
      format.html { redirect_to countries_path, notice: "Country was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.expect(country: [ :name ])
    end
end

app/controllers/souvenirs_controller.rb
class SouvenirsController < ApplicationController
  before_action :set_souvenir, only: %i[ show edit update destroy ]

  # GET /souvenirs or /souvenirs.json
  def index
    @souvenirs = Souvenir.all
  end

  # GET /souvenirs/1 or /souvenirs/1.json
  def show
  end

  # GET /souvenirs/new
  def new
    @souvenir = Souvenir.new
  end

  # GET /souvenirs/1/edit
  def edit
  end

  # POST /souvenirs or /souvenirs.json
  def create
    @souvenir = Souvenir.new(souvenir_params)

    respond_to do |format|
      if @souvenir.save
        format.html { redirect_to @souvenir, notice: "Souvenir was successfully created." }
        format.json { render :show, status: :created, location: @souvenir }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @souvenir.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /souvenirs/1 or /souvenirs/1.json
  def update
    respond_to do |format|
      if @souvenir.update(souvenir_params)
        format.html { redirect_to @souvenir, notice: "Souvenir was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @souvenir }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @souvenir.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /souvenirs/1 or /souvenirs/1.json
  def destroy
    @souvenir.destroy!

    respond_to do |format|
      format.html { redirect_to souvenirs_path, notice: "Souvenir was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_souvenir
      @souvenir = Souvenir.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def souvenir_params
      params.expect(souvenir: [ :name, :pic ])
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]

  # GET /trips or /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1 or /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: "Trip was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy!

    respond_to do |format|
      format.html { redirect_to trips_path, notice: "Trip was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.expect(trip: [ :content, :language, :country_id, :job_id, :myjob ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/souvenirs_helper.rb
module SouvenirsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>

</div>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<% content_for :title, "Editing country" %>

<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Countries" %>

<h1>Countries</h1>

<div id="countries">
  <% @countries.each do |country| %>
    <%= render country %>
    <p>
      <%= link_to "Show this country", country %>
    </p>
  <% end %>
</div>

<%= link_to "New country", new_country_path %>

app/views/countries/new.html.erb
<% content_for :title, "New country" %>

<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<div>
  <%= link_to "Edit this country", edit_country_path(@country) %> |
  <%= link_to "Back to countries", countries_path %>

  <%= button_to "Destroy this country", @country, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Amazon Rails Gem" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<%=link_to "mes souvenirs", souvenirs_path%>
<%=link_to "mes destinations", trips_path%>
    <%= yield %>
  </body>
</html>

app/views/souvenirs/_form.html.erb
<%= form_with(model: souvenir) do |form| %>
  <% if souvenir.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(souvenir.errors.count, "error") %> prohibited this souvenir from being saved:</h2>

      <ul>
        <% souvenir.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :pic, style: "display: block" %>
    <%= form.text_field :pic %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/souvenirs/_souvenir.html.erb
<div id="<%= dom_id souvenir %>">
  <p>
    <strong>Name:</strong>
    <%= souvenir.name %>
  </p>

  <p>
    <strong>Pic:</strong>
    <%= souvenir.pic %>
  </p>

</div>

app/views/souvenirs/edit.html.erb
<% content_for :title, "Editing souvenir" %>

<h1>Editing souvenir</h1>

<%= render "form", souvenir: @souvenir %>

<br>

<div>
  <%= link_to "Show this souvenir", @souvenir %> |
  <%= link_to "Back to souvenirs", souvenirs_path %>
</div>

app/views/souvenirs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Souvenirs" %>

<h1>Souvenirs</h1>
<p>si tu es tres sportif-ve ou voyageu-se, peux tu te rappeler des animaux, bds, montagnes ou tu es allée en voyage, trouver une image pour les lister ici., endroits où tu partie en séjour de sport, etc.</p>

<div id="souvenirs">
  <% @souvenirs.each do |souvenir| %>
    <%= render souvenir %>
    <p>
      <%= link_to "Show this souvenir", souvenir %>
    </p>
  <% end %>
</div>

<%= link_to "New souvenir", new_souvenir_path %>

app/views/souvenirs/new.html.erb
<% content_for :title, "New souvenir" %>

<h1>New souvenir</h1>

<%= render "form", souvenir: @souvenir %>

<br>

<div>
  <%= link_to "Back to souvenirs", souvenirs_path %>
</div>

app/views/souvenirs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @souvenir %>

<div>
  <%= link_to "Edit this souvenir", edit_souvenir_path(@souvenir) %> |
  <%= link_to "Back to souvenirs", souvenirs_path %>

  <%= button_to "Destroy this souvenir", @souvenir, method: :delete %>
</div>

app/views/trips/_form.html.erb
<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :language, style: "display: block" %>
    <%= form.text_field :language %>
  </div>

  <div>
    <%= form.label :country_id, style: "display: block" %>
    <%= form.number_field :country_id %>
  </div>

  <div>
    <%= form.label :job_id, style: "display: block" %>
    <%= form.text_field :myjob %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<div id="<%= dom_id trip %>">
  <p>
    <strong>Content:</strong>
    <%= trip.content %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= trip.language %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= trip.country_id %>
  </p>

  <p>
    <strong>Job:</strong>
    <%= trip.job_id %>
  </p>

</div>

app/views/trips/edit.html.erb
<% content_for :title, "Editing trip" %>

<h1>Editing trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Show this trip", @trip %> |
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Trips" %>

<h1>Trips</h1>
<p>prete pour laventure, il y a un detecteur de langue dans ce formulaire, parle la langue que tu veux dans ce formulaire, pour pouvoir partir dans la destination que tu choisis avec ce job.</p>

<div id="trips">
  <% @trips.each do |trip| %>
    <%= render trip %>
    <p>
      <%= link_to "Show this trip", trip %>
    </p>
  <% end %>
</div>

<%= link_to "New trip", new_trip_path %>

app/views/trips/new.html.erb
<% content_for :title, "New trip" %>

<h1>New trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trip %>

<div>
  <%= link_to "Edit this trip", edit_trip_path(@trip) %> |
  <%= link_to "Back to trips", trips_path %>

  <%= button_to "Destroy this trip", @trip, method: :delete %>
</div>